<?php
// For each client, get the client secret.
$clientSecret["42"] = "somthingthatshouldbeverylongandrandom";

// For the servers, this is the sercret key
$secretKeyServer = "";
?>
<html>
<head>
<title>Auth server</title>
</head>

<body>
<h1>Hi and welcome to the authz server.</h1>
<?php


if (isset($_GET['action'])){
    $action = $_GET['action'];

    switch($action){
        case "redirect":
            handleRedirect();
            break;
        default:
            handleDefault();
    }
} else if (isset($_POST['commit'])){
    // Check of user credentials are corret
    $username = $_POST['username'];
    $password = $_POST['password'];
    $correctLogin = $username == "ole" && $password == "bole";

    if(!$correctLogin) {
        echo "Not correct credentials.";
    } else {
        $clientId = $_POST["clientid"];
        $responsetype = $_POST["responsetype"];
        $scope = $_POST["scope"];

        handleCorrectLogin($clientId, $responsetype, $scope, $username);
    }
} else {
    // An actions hasn't been set, and there hasn't been amy attempt to log on


    echo '<p>Here you can login to authorize yoursef.</p>';

}


?>
</body>
</html>
<?php

function handleRedirect()
{
    $clientId = $_GET['clientid'];
    $responseType = $_GET['responsetype'];
    $scope = $_GET['scope'];


    $clientName = "undefined";
    switch($clientId){
        case "42":
            $clientName = "BookFace";
    }

    $scopeText = "undefined";
    switch($scope){
        case "1":
            $scopeText = "<li>First name</li>";
            break;
        case "2":
            $scopeText = "<li>First name</li><li>Last name</li>";
            break;
        case "3":
            $scopeText = "<li>First name</li><li>Last 
                name</li><li>Birthday</li>";
            break;
    }

    // The user should now get to authorize 
    echo "Would you like to give <b>" . $clientName . "</b> access to: 
        <ul> " . $scopeText . "</li><br />";

    echo "Then please login using the following form:";
    echo '
        <form method="post" action="authz.php">
        <input name="username" type="text" value="" placeholder="Username">
        <input name="password" type="password" value="" placeholder="Password">
        <input name="clientid" type="hidden" value="' . $clientId . '">
        <input name="responsetype" type="hidden" value="' . $responseType . '">
        <input name="scope" type="hidden" value="' . $scope . '">
        <input name="commit" type="submit" value="Accept by login">
        </form>
        ';
    

    
}

function handleCorrectLogin($clientId, $responseType, $scope, $username)
{
    echo $clientId;
    echo $responseType;
    echo $scope;
    echo $username;

    // Generate authz token
    // Need to contain a hash of clientID, scope, and username
    // Use salt as same length of 
    $stringToHash = $clientId . $scope . $username;

    // TODO: autogererate the salt, and store.
    $salt = "thisshouldbeautogenerated";
    $options = [
        'salt' => $salt,
    ];
    $hashedString = hash("sha256", $stringToHash . $salt);

    echo '<script type="text/javascript">
        window.location = ' . 
        '"client.php' . 
         '?action=authzcode' .
         '&code=' . $hashedString . 
         '&scope=' . $scope . 
        '"
      </script>';


    // Properties of the authztoken:
    // It's a token to see that the user has authorized the client on some scope
    // hence, wee need to have:
    // * The user
    // * The client
    // * The scope


}


function handleDefault()
{
    echo "<p>Action not defined</p><br />Get parameters: <br />";
    foreach($_GET as $key => $value){
        echo $key . " : " . $value . "<br />\r\n";
    }
}

?>
